---
title: "Simulating metaSPARSim datasets"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/n/janson_lab/lab/sma/sparsedossa_paper/")
knitr::opts_chunk$set(echo=FALSE)
library(magrittr)
library(ggplot2)
```

```{r setup2}
# Registry
# batchtools::makeRegistry(file.dir = "results/sim_metaSPARSim",
#                          package = "magrittr")
batchtools::loadRegistry(file.dir = "results/sim_metaSPARSim", 
                         writeable = TRUE)
batchtools::clearRegistry()

# Grid parameters
ncpus <- 1
partition <- "janson_bigmem"
walltime <- 5 * 3600

dir_output <- "/n/janson_lab/lab/sma/sparsedossa_paper/results/sim_metaSPARSim/"
dir.create(dir_output, recursive = TRUE)
```

```{r job grid}
set.seed(1)
tb_job <- tidyr::expand_grid(
  name = c("stool",
           "vaginal"),
  R = seq(1, 100)
) %>% 
  dplyr::mutate(i_job = seq_len(dplyr::n()))
```

```{r define one job}
one_job <- function(i_job) {
  set.seed(i_job)
  
  i_tb_job <- tb_job[tb_job$i_job == i_job, ]
  load(paste0("results/fits/", i_tb_job$name, "_fit_metaSPARSim.RData"))
  
  sim_metaSPARSim <- metaSPARSim::metaSPARSim(fit_metaSPARSim)
  save(sim_metaSPARSim, file = paste0(dir_output, i_job, ".RData"))
}
```

```{r submit jobs}
tb_ids <- batchtools::batchMap(one_job,
                               i_job = tb_job$i_job)
batchtools::batchExport(mget(ls()))
batchtools::submitJobs(ids = tb_ids$job.id,
                       resources =  list(ncpus = ncpus, 
                                         partition = partition, 
                                         walltime = walltime))
```