---
title: "Fit and compare different methods"
author: "Siyuan Ma"
date: "8/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/Users/Siyuan/Git/sparsedossa2_paper/")
knitr::opts_chunk$set(echo=FALSE)
library(magrittr)
library(ggplot2)
```

```{r load stool and vaginal}
load("data/physeqs/HMP1II_stool.RData")
load("data/physeqs/HMP1II_vaginal.RData")

x_samples_stool <- physeq_stool %>% 
  smar::otu_table2() 
# subset to top 200 samples and 250 features
x_samples_stool <- 
  x_samples_stool[, 
                  order(-apply(x_samples_stool, 2, sum))[seq(1, 200)]]
x_samples_stool <- 
  x_samples_stool[apply(x_samples_stool > 0, 1, sum) >= 2, ]
x_samples_stool <- 
  x_samples_stool[apply(x_samples_stool, 2, SparseDOSSA2:::TSS) %>% 
                      apply(1, mean) %>% 
                      {order(-.)[1:250]}, ]

x_samples_vaginal <- physeq_vaginal %>% 
  smar::otu_table2() 
# subset to top 200 samples and 250 features
x_samples_vaginal <- 
  x_samples_vaginal[, 
                  order(-apply(x_samples_vaginal, 2, sum))[seq(1, 200)]]
x_samples_vaginal <- 
  x_samples_vaginal[apply(x_samples_vaginal > 0, 1, sum) >= 2, ]
x_samples_vaginal <- 
  x_samples_vaginal[apply(x_samples_vaginal, 2, SparseDOSSA2:::TSS) %>% 
                      apply(1, mean) %>% 
                      {order(-.)[1:250]}, ]
```

```{r fit to data}
list(x_samples_stool, x_samples_vaginal) %>% 
  purrr::map2(c("stool", "vaginal"),
              function(dataset, name) {
                # fit metaSPARSim
                # dataset_norm_factor <- GMPR(dataset)
                # dataset_norm <- t(t(dataset) / dataset_norm_factor)
                # fit_metaSPARSim <- metaSPARSim::estimate_parameter_from_data(
                #   raw_data = dataset,
                #   norm_data = dataset_norm,
                #   conditions = list("group" = colnames(dataset)))
                # sim_metaSPARSim <- metaSPARSim::metaSPARSim(fit_metaSPARSim)
                
                # fit SparseDOSSA
                if(name == "stool") {
                  load("data/hmp1-II/fit_6.RData")
                  fit_SparseDOSSA <- fit_EM
                } else {
                  load("data/hmp1-II/fit_5.RData")
                  fit_SparseDOSSA <- fit_EM
                }
                save(fit_SparseDOSSA, 
                     file = paste0("results/fits/",
                                   name, 
                                   "_fit_SparseDOSSA.RData"))
                
                # fit mvn
                dataset_transform <- log(apply(dataset + 0.5, 2, function(x) x/sum(x)))
                mean_mvn <- apply(dataset_transform, 1, mean)
                cov_mvn <- cov(t(dataset_transform))
                cov_penalized <- huge::huge(t(dataset_transform),
                                            nlambda = 10,
                                            method = "glasso")
                cov_opt <- solve(huge::huge.select(cov_penalized,
                                                   criterion = "ebic")$opt.icov)
                fit_mvn <- list(mean_mvn = mean_mvn,
                                cov_mvn = cov_opt)
                save(fit_mvn,
                     file = paste0("results/fits/",
                                   name, 
                                   "_fit_mvn.RData"))
                return(NULL)
              })
```
```{r simulate multiple dataset to compare against R2}
R <- 500
c("stool", "vaginal") %>% 
  purrr::map2(list(x_samples_stool,
                   x_samples_vaginal),
              function(name, dataset) {
                # fit metaSPARSim
                # dataset_norm_factor <- GMPR(dataset)
                # dataset_norm <- t(t(dataset) / dataset_norm_factor)
                # fit_metaSPARSim <- metaSPARSim::estimate_parameter_from_data(
                #   raw_data = dataset,
                #   norm_data = dataset_norm,
                #   conditions = list("group" = colnames(dataset)))
                # sim_metaSPARSim <- metaSPARSim::metaSPARSim(fit_metaSPARSim)
                
                # evaluate SparseDOSSA
                load(paste0("results/fits/", name,
                            "_fit_SparseDOSSA.RData"))
                R2s_SparseDOSSA <- seq(1, 100) %>% 
                  purrr::map_dbl(~ {
                    a_samples <- SparseDOSSA2:::generate_a(
                      n = ncol(dataset),
                      feature_param = 
                        as.data.frame(fit_SparseDOSSA$fit[c("pi0", "mu", "sigma")]),
                      Omega = fit_SparseDOSSA$fit$Omega)
                    x_samples <- apply(a_samples, 2, SparseDOSSA2:::TSS)
                    dataset_combined <- 
                      cbind(apply(dataset, 2, SparseDOSSA2:::TSS),
                            x_samples)
                    D <- vegan::vegdist(t(dataset_combined), method = "bray")
                    R2 <- vegan::adonis(D ~ sample,
                                        data = data.frame(sample = rep(c("original",
                                                                         "simulation"),
                                                                       each = ncol(dataset))),
                                        permutations = 2)$aov.tab$R2[1]
                    R2
                  })
                save(R2s_SparseDOSSA, 
                     file = paste0("results/Simu/",
                                   name, "_R2_SparseDOSSA.RData"))
                
                # evaluate mvn
                load(paste0("results/fits/", name,
                            "_fit_mvn.RData"))
                R2s_mvn <- seq(1, 100) %>% 
                  purrr::map_dbl(~ {
                    a_samples <- mvtnorm::rmvnorm(n = ncol(dataset),
                                                  mean = fit_mvn$mean_mvn,
                                                  sigma = fit_mvn$cov_mvn %>% 
                                                    SparseDOSSA2:::enforce_symm()) %>% 
                      exp() %>% 
                      t()
                    x_samples <- apply(a_samples, 2, SparseDOSSA2:::TSS)
                    dataset_combined <- 
                      cbind(apply(dataset, 2, SparseDOSSA2:::TSS),
                            x_samples)
                    D <- vegan::vegdist(t(dataset_combined), method = "bray")
                    R2 <- vegan::adonis(D ~ sample,
                                        data = data.frame(sample = rep(c("original",
                                                                         "simulation"),
                                                                       each = ncol(dataset))),
                                        permutations = 2)$aov.tab$R2[1]
                    R2
                  })
                save(R2s_mvn, 
                     file = paste0("results/Simu/",
                                   name, "_R2_mvn.RData"))
                
              })
```

```{r panels for comparison}
set.seed(1)
l_p <- c("stool", "vaginal") %>% 
  purrr::map2(list(x_samples_stool,
                   x_samples_vaginal),
              function(name, dataset) {
                
                # simulate SparseDOSSA
                load(paste0("results/fits/", name,
                            "_fit_SparseDOSSA.RData"))
                
                a_samples <- SparseDOSSA2:::generate_a(
                  n = ncol(dataset),
                  feature_param = 
                    as.data.frame(fit_SparseDOSSA$fit[c("pi0", "mu", "sigma")]),
                  Omega = fit_SparseDOSSA$fit$Omega)
                x_samples_SparseDOSSA <- apply(a_samples, 2, SparseDOSSA2:::TSS)
                dataset_combined <- 
                  cbind(apply(dataset, 2, SparseDOSSA2:::TSS),
                        x_samples_SparseDOSSA)
                D <- vegan::vegdist(t(dataset_combined), method = "bray")
                R2_SparseDOSSA <- vegan::adonis(D ~ sample,
                                                data = data.frame(sample = rep(c("original",
                                                                                 "simulation"),
                                                                               each = ncol(dataset))),
                                                permutations = 2)$aov.tab$R2[1]
                
                load(paste0("results/fits/", name,
                            "_fit_mvn.RData"))
                a_samples <- mvtnorm::rmvnorm(n = ncol(dataset),
                                              mean = fit_mvn$mean_mvn,
                                              sigma = fit_mvn$cov_mvn %>% 
                                                SparseDOSSA2:::enforce_symm()) %>% 
                  exp() %>% 
                  t()
                x_samples_mvn <- apply(a_samples, 2, SparseDOSSA2:::TSS)
                dataset_combined <- 
                  cbind(apply(dataset, 2, SparseDOSSA2:::TSS),
                        x_samples_mvn)
                D <- vegan::vegdist(t(dataset_combined), method = "bray")
                R2_mvn <- vegan::adonis(D ~ sample,
                                        data = data.frame(sample = rep(c("original",
                                                                         "simulation"),
                                                                       each = ncol(dataset))),
                                        permutations = 2)$aov.tab$R2[1]
                
                dataset_combined <- 
                  cbind(apply(dataset, 2, SparseDOSSA2:::TSS),
                        x_samples_SparseDOSSA,
                        x_samples_mvn)
                D <- vegan::vegdist(t(dataset_combined), method = "bray")
                fit_pcoa <- ape::pcoa(D = D)$vectors[, 1:2] %>% as.data.frame()
                fit_pcoa$dataset <- rep(c("Original", "SparseDOSSA 2", "Logist MVN"),
                                        each = ncol(dataset)) 
                fit_pcoa <- fit_pcoa %>% dplyr::mutate(dataset = factor(dataset,
                                                                        levels = c("Original",
                                                                                   "SparseDOSSA 2",
                                                                                   "Logist MVN")))
                p1 <- 
                  fit_pcoa %>%
                  ggplot(aes(x = Axis.1, y = Axis.2, color = dataset,
                             alpha = dataset)) +
                  geom_point() +
                  scale_color_manual(values = c("Original" = "black",
                                                "SparseDOSSA 2" = "red",
                                                "Logist MVN" = "red")) +
                  scale_alpha_manual(values = c("Original" = 1,
                                                "SparseDOSSA 2" = 1,
                                                "Logist MVN" = 0)) +
                  theme_bw() +
                  theme(legend.position = c(1, 1),
                        legend.justification = c(1, 1),
                        legend.background = element_blank()) +
                  # coord_fixed() +
                  xlab("Axis 1") +
                  ylab("Axis 2") +
                  ggtitle(paste0("R2 (SparseDOSSA 2 vs. Original) = ",
                          round(R2_SparseDOSSA * 100, 2),
                          "%"))
                
                p2 <- 
                  fit_pcoa %>%
                  ggplot(aes(x = Axis.1, y = Axis.2, color = dataset,
                             alpha = dataset)) +
                  geom_point() +
                  scale_color_manual(values = c("Original" = "black",
                                                "SparseDOSSA 2" = "red",
                                                "Logist MVN" = "red")) +
                  scale_alpha_manual(values = c("Original" = 1,
                                                "SparseDOSSA 2" = 0,
                                                "Logist MVN" = 1)) +
                  theme_bw() +
                  theme(legend.position = c(1, 1),
                        legend.justification = c(1, 1),
                        legend.background = element_blank()) +
                  # coord_fixed() +
                  xlab("Axis 1") +
                  ylab("Axis 2") +
                  ggtitle(paste0("R2 (Logist MVN vs. Original) = ",
                          round(R2_mvn * 100, 2),
                          "%"))
                
                load(paste0("results/Simu/",
                            name, "_R2_SparseDOSSA.RData"))
                load(paste0("results/Simu/",
                            name, "_R2_mvn.RData"))
                p3 <- data.frame(R2s = c(R2s_SparseDOSSA,
                                         R2s_mvn),
                                 class = rep(c("SparseDOSSA 2",
                                               "LogistMVN"),
                                             each = 100) %>% 
                                   factor(levels = c("SparseDOSSA 2",
                                                     "LogistMVN"))) %>% 
                  ggplot(aes(x = class, y = R2s)) +
                  geom_boxplot() +
                  theme_bw() +
                  ylab("R2") +
                  theme(axis.title.x = element_blank())
                cowplot::plot_grid(p1, p2, p3, nrow = 1)
              })
```

```{r plot per-feature params}
l_p2 <- c("stool", "vaginal") %>% 
  purrr::map(function(name) {
                
                if(name == "stool") {
                  load("data/hmp1-II/fit_2.RData")
                } else {
                  load("data/hmp1-II/fit_1.RData")
                }
    feature_param_template <- cbind(pi0 = fit_EM$fit$pi0, 
        mu = fit_EM$fit$mu, sigma = fit_EM$fit$sigma)
    F_fit <- SparseDOSSA2:::fit_F(feature_param = cbind(pi0 = fit_EM$fit$pi0, 
        mu = fit_EM$fit$mu, sigma = fit_EM$fit$sigma))
    F_samples <- SparseDOSSA2:::generate_featureParam(
      F_fit = F_fit, 
      param_original = feature_param_template, n_feature = 10000)
    rbind(feature_param_template %>% as.data.frame() %>% 
            dplyr::mutate(Class = "Original"),
          F_samples %>% as.data.frame() %>% 
            dplyr::mutate(Class = "SparseDOSSA 2")) %>% 
      dplyr::mutate(Class = factor(Class, levels = c("Original",
                                                     "SparseDOSSA 2"))) %>% 
      tidyr::pivot_longer(cols = c(pi0, mu, sigma),
                          names_to = "param",
                          values_to = "Parameter_value") %>% 
      ggplot(aes(x = Parameter_value, color = Class, fill = Class)) +
      geom_density(alpha = 0.5) +
      scale_fill_manual(values = c("Original" = "grey",
                                   "SparseDOSSA 2" = "red")) +
      scale_color_manual(values = c("Original" = "grey",
                                   "SparseDOSSA 2" = "red")) +
      facet_wrap(~param,
                 nrow = 1,
                 scales = "free") +
      theme_bw() +
      theme(axis.title.x = element_blank(),
            legend.position = c(1, 1),
            legend.justification = c(1, 1),
            legend.background = element_blank()) +
      ylab("Density") +
      ggtitle("Per-feature parameters")
              })

cowplot::plot_grid(cowplot::plot_grid(l_p[[1]], l_p2[[1]], ncol = 1),
                   cowplot::plot_grid(l_p[[2]], l_p2[[2]], ncol = 1),
                   ncol = 1) %>% 
  ggsave("figures/Fig2/Fig2.pdf",
         .,
         width = 12,
         height = 14)
```