---
title: "Fit SparseDOSSA 2 full datasets"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE)
library(magrittr)
library(ggplot2)
```

```{r setup2, include=FALSE}
# Registry
# batchtools::makeRegistry(file.dir = "r_batchtools_reg/fit_SparseDOSSA2_full/",
#                          package = "magrittr")
batchtools::loadRegistry(file.dir = "r_batchtools_reg/fit_SparseDOSSA2_full/", 
                         writeable = TRUE)
batchtools::clearRegistry()

# Grid parameters
ncpus <- 30
partition <- "shared"
walltime <- 48 * 3600

# Output dir
dir_output <- "results/fitted/SparseDOSSA2_full/"
dir.create(dir_output, recursive = TRUE, showWarnings = FALSE)
```

```{r setup simulation params}
tb_job <-
  tidyr::expand_grid(
    dataset = c("stool", "vaginal", "IBD"),
    lambdas = 10^seq(from = 0, to = -3, length.out = 7)
  ) %>% 
  dplyr::mutate(i_job = seq_len(dplyr::n()))
save(tb_job, file = paste0(dir_output, "tb_job.RData"))
```

```{r simulation task}
one_job <- function(i_job) {
  future::plan(list(future::sequential, future::sequential, future::multicore))
  i_tb_job <- tb_job[i_job, ]
  
  load(paste0("data/physeqs/", i_tb_job$dataset, ".RData"))
  x_samples <- 
    get(paste0("physeq_", i_tb_job$dataset, "_bl")) %>%
    smar::otu_table2()
  
  # fit SparseDOSSA 2
  fit_EM <- SparseDOSSA2::fitCV_SparseDOSSA2(
    data = x_samples,
    lambdas = i_tb_job$lambdas,
    K = 5,
    control = list(abs_tol = 1e-2,
                   rel_tol = 1e-3,
                   maxit = 50,
                   verbose = TRUE,
                   debug_dir = paste0(dir_output, i_job, "/")))
  save(fit_EM, file = paste0(dir_output, "fit_", i_job, ".RData"))
}
```

```{r submit jobs}
tb_ids <- batchtools::batchMap(one_job, 
                               i_job = tb_job$i_job)
batchtools::batchExport(mget(ls()))
batchtools::submitJobs(resources =  list(ncpus = ncpus, 
                                         partition = partition, 
                                         walltime = walltime))
```